#ifndef _LVForms_h
#define _LVForms_h
#include "LVCCG.h"
#include "CCGDataSupport.h"
#include "LVGlobs.h"

extern TextPtr KB___________VIName;
extern eRunStatus KB___________Start(subVIInstanceDataPtr viInstanceData, Boolean bShowFrontPanel, Boolean bRunToFinish, ArgList *argsIn, ArgList *argsOut, Boolean *pause);
#define KB___________formID 2000

extern TextPtr NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_VIName;
extern eRunStatus NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_Run(
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_0_error_in__no_error__1, cl_00000  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_0_error_in__no_error__1,
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_1_A_1D_U32_array_53, PDAArrPtr  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_1_A_1D_U32_array_53,
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_2_A_2D_U32_array_AE, PDAArrPtr  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_2_A_2D_U32_array_AE,
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_3_U32_value_4C, uInt32  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_3_U32_value_4C,
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_4_Color_Mode_6, uInt16  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_in_4_Color_Mode_6,
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_out_0_A_2D_Color_value_array_8C, PDAArrPtr*  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_out_0_A_2D_Color_value_array_8C,
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_out_1_A_1D_Color_value_array_2C, PDAArrPtr*  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_out_1_A_1D_Color_value_array_2C,
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_out_2_error_out_78, cl_00000*  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_out_2_error_out_78,
				DataType dtNI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_out_3_Color_Value_15, cl_A0000*  NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_out_3_Color_Value_15	);
#define NI_Vision_Development_Module_lvlib_IMAQ_IntegerToColorValue_formID 2100
